"""Portmanteau

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SA83JJiEcRatoc1E3Y10FF9EZTX39Bgm

# Character Seq Model
"""

#@title Imports
from __future__ import print_function
from portmanteau import bridge

line = "==========================="
while True:
    print (line + '\n' + line)
    w1 = raw_input("Word 1 : ")
    w2 = raw_input("Word 2 : ")
    bridge(w1, w2)
    if raw_input(line + "\nPress 'q' to quit. 'Enter' to try again : ") == 'q':
        break
